project:
  type: website
  output-dir: docs
execute:
  freeze: auto
resources:
  - CNAME
  - assets/*
  - demos/images/**/*
website:
  title: "Data Studio 2024"
  twitter-card:
    creator: "@dangerscarf"
  search: true
  navbar:
    background: light
    search: true
    # left:
    #   - text: "Intro"
    #     file: intro/index.qmd
    #   - text: "Text"
    #     file: text/index.qmd
    #   - text: "Images"
    #     file: images/index.qmd
    #   - text: "Audio"
    #     file: audio/index.qmd
    #   - text: "Video"
    #     file: video/index.qmd
    #   - text: "Custom"
    #     file: diy/index.qmd
  sidebar:
    style: docked
    align: left
    border: false
    collapse-level: 3
    contents:
      - text: "Home"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus.md
      # - section: "Prompting"
      #   file: headlines/index.qmd
      #   contents:
      #     - text: The value of chat
      #       file: headlines/basics.qmd
      #     - file: headlines/prompt-engineering.qmd
      #     - file: headlines/rule-of-five.qmd
      #     - file: headlines/conversations.qmd
      #     - file: headlines/conclusion.qmd
      # # - section: "How it works"
      #   file: how-it-works/index.qmd
      # - section: "Semantic search"
      #   contents:
      #     - file: semantic-search/explanation.qmd
      # - section: "Experimenting and sharing"
      #   contents:
      #     - text: Intro
      #       file: demos/010-intro.qmd
      #     - text: Automatic demos
      #       file: demos/020-auto-spaces.qmd
      #     - text: Custom model pages
      #       contents:
      #       - text: "01: Basic demos"
      #         file: demos/030-learning-gradio.qmd
      #       - text: "02: Adjusting outputs"
      #         file: demos/035-gradio-inputs.qmd
      # - section: "Introduction"
      #   contents:
      #   - file: intro/index.qmd
      #   - text: "What is a model?"
      #     file: intro/models.qmd
      #   - text: "Training a model"
      #     file: intro/fine-tune-model.qmd
      # - section: "Existing models"
      #   contents:
      #   - text: "How to use"
      #     file: existing-models.qmd
      #   - section: "ðŸ“ Text"
      #     contents:
      #     - text/index.qmd
      #     - text: "Classifying"
      #       file: text/text-classification.qmd
      #     - text: "Extracting people and organizations"
      #       file: text/named-entity-recognition.qmd
      #     - text: "Document similarity"
      #       file: text/document-similarity.qmd
      #     - text: "Asking PDFs questions"
      #       file: text/asking-pdfs-questions.qmd
      #     - text: "Asking documents questions"
      #       file: text/asking-documents-questions.qmd
      #   - section: "ðŸ–¼ï¸ Images"
      #     contents:
      #     - images/index.qmd
      #     - text: "Classifying"
      #       file: images/image-classification.qmd
      #     - text: "Asking questions"
      #       file: images/vqa.qmd
      #     - text: "Counting things"
      #       file: images/instance-segmentation.qmd
      #     - text: "Measuring amounts"
      #       file: images/semantic-segmentation.qmd
      #     - text: "Describing images"
      #       file: images/image-description.qmd
      #   - section: "ðŸ”Š Audio"
      #     contents:
      #     - audio/index.qmd
      #     - text: "Transcription"
      #       file: audio/transcription.qmd
      #     - text: "Noise removal"
      #       file: audio/removing-noise.qmd
      #   - section: "ðŸŽ¬ Video"
      #     contents:
      #     - video/index.qmd
      # - section: "Build your own"
      #   contents:
      #   - text: "Customization overview"
      #     file: diy/index.qmd  
      #   - text: "Text classifier"
      #     file: diy/text-classification.qmd
      #   - text: "Image classifier"
      #     file: diy/image-classification.qmd
      #   - text: "Exploring the possibilities"
      #     file: diy/research.qmd
      #   - text: "Custom tools"
      #     file: diy/custom.qmd  
  page-footer: 
    border: false
    background: dark
    left: >
      Find me at [jonathan.soma@gmail.com](mailto:jonathan.soma@gmail.com)
      or [@dangerscarf](https://twitter.com/dangerscarf)
    center: >
      Â©2023, Jonathan Soma
    right: 
      - icon: github
        href: https://github.com/jsoma
      - icon: twitter 
        href: https://twitter.com/dangerscarf
      - icon: envelope
        href: mailto:jonathan.soma@gmail.com
format:
  html:
    code-overflow: wrap
    # template-partials:
    #   - partials/title-block.html
    callout-appearance: simple
    # fontsize: 1.1em;
    # toc: false
    # toc-title: Table of contents
    theme:
      - cosmo
      # - lumen
      # - quartz
      - custom.scss
    css: static/style.css
    number-sections: false
    # grid:
    #   sidebar-width: 350px
    #   body-width: 900px
    #   margin-width: 250px
